name: Get Blowfish Config

on:
  workflow_dispatch:

jobs:
  download-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download config zip
        run: |
          curl -L -o config.zip https://github.com/nunocoracao/blowfish/releases/latest/download/config-default.zip

      - name: Extract config
        run: |
          rm -rf config/_default/*
          unzip config.zip -d config/_default

      - name: Commit if changes exist
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add config/_default

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add Blowfish default config"
            git push
          fi
